// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fihehymcuiiosltnpxgk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpaGVoeW1jdWlpb3NsdG5weGdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMTYyMTIsImV4cCI6MjA1Nzg5MjIxMn0.cd3c9PvJO4CdIp11x4QJ_hs803CkhZwVLy_5WE8ikrM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);